CREATE SCHEMA IF NOT EXISTS `pzdb` DEFAULT CHARACTER SET utf8 ;
USE `pzdb`;
CREATE TABLE IF NOT EXISTS role (
  roleid INT NOT NULL AUTO_INCREMENT,
  role VARCHAR(255) NOT NULL,
  PRIMARY KEY (roleid)
);

CREATE TABLE IF NOT EXISTS user (
  userid INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  surname VARCHAR(255) NOT NULL,
  role_id INT(255) NOT NULL,
  PRIMARY KEY (userid),
  CONSTRAINT fk_user_role FOREIGN KEY(role_id) REFERENCES role(roleid)
);
